### PR TITLE
Style and functionality improvements.

### PR DESCRIPTION
**Pull request by nphyx**
Hey, made a few small improvements. Notes from my commits:

* styled password input to match theme
* styled radio selects for DE to match theme
* defaults to last used DE instead of default DE
* if password is filled when DE is selected, login starts automatically (instead of having to re-focus password and press enter to submit)
* install script copies files to recommended directory
* renamed background image to be more generic
* attempted to support background image configuration, but it didn't
work (commented out for later review)

### CODE REVIEW

**Comment by oblitum** [comment]
This pull request made users vanish from the login screen for me, leaving no way to choose any user to login. I had to revert it.

**Comment by oblitum** [comment]
Ah, checking changes, so it's now webkit2... will try to install it and then check.

**Comment by oblitum** [comment]
OK, didn't expect it by just updating the plugin, but for anyone interested, from this commit onwards:

- Install `lightdm-webkit2-greeter` (and potentially remove `lightdm-webkit-greeter`. I did)
- Change `/etc/lightdm/lightdm.conf` to use webkit2
- Configure `/etc/lightdm/lightdm-webkit2-greeter.conf` to use the arch theme (and potentially remove the older `lightdm-webkit-greeter.conf`)

**Comment by oblitum** [comment]
README and potentially any other docs are now invalid. This commit should have documented this change on the pull and changed docs accordingly.

**Comment by nphyx** [comment]
IIRC I updated to lightdm-webkit2-greeter in order to get the theme to install in the first place (before making my own changes), but you're right, I overlooked the documentation. I'll correct and submit a new pull request.

**Pull request merged**
